apiVersion: v1
kind: Service
metadata:
  labels:
    app-service: color-service
  name: color-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8081
  type: NodePort
  selector:
    app-service: color-service
