apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-service: color-service
  name: color-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app-service: color-service
  strategy: {}
  template:
    metadata:
      labels:
        app-service: color-service
    spec:
      containers:
        - env:
            - name: SPOILER_TYPE
              value: NONE
            - name: SPOILER_MTTF
              value: "1000"
          image: docker.io/izderadicka/color-service:latest
          imagePullPolicy: IfNotPresent
          name: color-service
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /color
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
          resources: {}
      restartPolicy: Always
