apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-service: heroes-service
  name: heroes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: heroes-service
  strategy: {}
  template:
    metadata:
      labels:
        app-service: heroes-service
    spec:
      containers:
        - env:
            - name: spring_profiles_active
              value: docker
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
          
          image: docker.io/izderadicka/heroes-service:latest 
          imagePullPolicy: IfNotPresent
          name: heroes-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
