apiVersion: v1
kind: Service
metadata:
  labels:
    app-service: heroes-service
  name: heroes-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app-service: heroes-service
  type: NodePort
