apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: heroesdemo
  name: heroesdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: heroesdemo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/postgres: "true"
        io.kompose.service: heroesdemo
    spec:
      containers:
        - env:
            - name: spring_profiles_active
              value: docker
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-user
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: username
          # this image is in local minikube registry 
          # used via registry plugin - minikube addon enable registry
          # to push from host:
          # 1)  echo "$(minikube ip)    minikube" | sudo tee -a /etc/hosts
          # 2) Add insecure registry to docker deamon config  /etc/docker/daemon.json:
          # {
          #   "insecure-registries" : ["minikube:5000"]
          # }
          # restart docker daemon
          # 4) docker push minikube:5000/heroesdemo
          #  
          # note that inside minikube registry host is locahost
          image: heroesdemo 
          imagePullPolicy: IfNotPresent
          name: heroesdemo
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
